# Generated by Django 4.1.7 on 2023-03-19 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0006_alter_task_habit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='habit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='registration.habit'),
        ),
    ]
