# Generated by Django 4.1.7 on 2023-03-26 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0007_alter_task_habit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='habits',
        ),
        migrations.RemoveField(
            model_name='category',
            name='tasks',
        ),
        migrations.AddField(
            model_name='habit',
            name='categories',
            field=models.ManyToManyField(to='registration.category'),
        ),
        migrations.AddField(
            model_name='task',
            name='categories',
            field=models.ManyToManyField(to='registration.category'),
        ),
    ]
