# Generated by Django 4.1.7 on 2023-03-30 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0013_alter_customuser_first_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='slug',
            field=models.SlugField(default='slug', max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='slug',
            field=models.SlugField(default='slug', max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
